number1 = input('Enter number 1')
number2 = input('Enter number 2')
print(number1,number2)
sum = number1 + number2
print(sum)
sum = int(number1) + int(number2)
print(sum)
difference = int(number1) - int(number2)
multiplication = int(number1) * int(number2)
division = int(number1) / int(number2)
print(difference,multiplication,division)
number3 = input('Enter number 3')
sum = int(number1) + int(number2) + int(number3)
difference = int(number1) - int(number2) - int(number3)
multiplication = int(number1) * int(number2) * int(number3)
division = (int(number1)/int(number2)) / int(number3)
print(sum,difference,multiplication,division)
import math
print(math.pow(9,3))
print(math.sqrt(25))
print(math.sin(25))
print(math.tan(25))
print(math.cos(25))
print(math.exp(2))
print(math.fabs(25))
print(math.log(10))
print(math.sinh(25))
print(math.tanh(25))
print(math.cosh(255))